# Generated by Django 4.2.7 on 2023-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='formacao_academica',
            field=models.CharField(choices=[('E', 'Estudante'), ('F', 'Professor')], default='E', max_length=30),
        ),
    ]
