# Generated by Django 4.2.7 on 2023-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_estudante_formacao_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
